# -*- coding: utf-8 -*-
"""Atribuicao_variáveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13kYLbJVwG_Kmv5wMBtZtwiKtArUn0hPY

# Configurações

## Pacotes

### Instalação
"""

!pip install geopandas

!pip install rasterstats

"""### Chamar"""

from google.colab import drive
from google.colab import files

import pandas as pd
import geopandas
from shapely import wkt

from rasterstats import  point_query

import copy

"""## Conexao com a pasta"""

drive.mount('/content/drive')

cd /content/drive/My Drive/PDPA

"""## Funções"""

# Criação de variáveis dicotômicas
def flg_func(value):
    if pd.isna(value):
        return 0
    else:
      return 1

"""#Arquivos"""

df_coordenadas_mapeadas = pd.read_csv('coordenadas_mapeadas.csv'
                     ,sep = ','
                     ,decimal='.'
                      )

df_coordenadas_mapeadas['geometry'] = df_coordenadas_mapeadas['geometry'].apply(wkt.loads)
gdf_coordenadas_mapeadas = geopandas.GeoDataFrame(df_coordenadas_mapeadas, crs='epsg:4326')

"""# Seleção das variáveis geomorfométricas"""

lista_arquivos_tif = ['22S435ZN.tif',
                      '22S435SN.tif',
                      '22S435ON.tif',
                      '22S435VN.tif',
                      '22S435HN.tif',
                      '22S435SA.tif',
                      '22S435SB.tif',
                      '22S435SC.tif',
                      '22S435OC.tif',
                      '22S435V3.tif',
                      '22S435V5.tif',
                      '22S435H3.tif',
                      '22S435H5.tif',
                      '22S435FT.tif',
                      '22S435RS.tif',
                      '22S435DD.tif']

lista_nome_variaveis = ['Altitude_numerica',
                      'Declividade_numerica',
                      'Orientacao_numerica',
                      'Curv_Vertical_numerica',
                      'Curv_Horizontal_numerica',
                      'Declividade_classes_A',
                      'Declividade_classes_B',
                      'Declividade_classes_C',
                      'Orientacao_octantes',
                      'Curv_Vertical_3classes',
                      'Curv_Vertical_5classes',
                      'Curv_Horizontal_3classes',
                      'Curv_Horizontal_5classes',
                      'Forma_de_terreno_classes',
                      'Relevo_sombreado_numerico',
                      'ADD_divisores_talvegues']

for variavel in range(len(lista_nome_variaveis)):
  df_coordenadas_mapeadas.loc[:,lista_nome_variaveis[variavel]]= point_query(df_coordenadas_mapeadas.loc[:,'geometry'], lista_arquivos_tif[variavel])

df_coordenadas_mapeadas.info()

#df_coordenadas_mapeadas['geometry'] = df_coordenadas_mapeadas['geometry'].apply(wkt.loads)
gdf_relevo = geopandas.GeoDataFrame(df_coordenadas_mapeadas, crs='epsg:4326')

"""# Informação de vegetação"""

gdf_vegetacao = geopandas.read_file("vege_area_mu_3303302.shp").to_crs(4326)

gdf_relevo_veg = geopandas.tools.sjoin(gdf_relevo, gdf_vegetacao[['leg_sup','legenda_1','legenda_2','geometry']], predicate="within", how='left')

_dummies = pd.get_dummies(gdf_relevo_veg, columns = None, drop_first = False)

_dummies = _dummies.rename(columns={"	leg_sup_Massa D´água": "Massa_Dagua"
                            , "leg_sup_Vegetação Natural Dominante": "Vegetacao_Natural_Dominante"
                            , "leg_sup_Área Antrópica Dominante": "Area_Antropica_Dominante"
                            , "legenda_1_Floresta Ombrófila Densa": "Floresta_Ombrofila_Densa"
                            , "legenda_1_Formação Pioneira": "Formacao_Pioneira"
                            , "legenda_2_Floresta Ombrófila Densa Submontana": "Floresta_Ombrofila_Densa_Submontana"
                            , "legenda_2_Formação Pioneira com influência fluviomarinha": "Formacao_Pioneira_com_influencia_fluviomarinha"
                            , "legenda_2_Influência urbana": "Influencia_urbana"
                            , "legenda_2_Vegetação Secundária": "Vegetacao_Secundaria"}).drop(["index_right", "legenda_2_Indiscriminada"], axis=1)

gdf_relevo = copy.deepcopy(_dummies)

del(gdf_relevo_veg); del(gdf_vegetacao); del(_dummies)

"""# Informação de Pedologia"""

gdf_pedologia = geopandas.read_file("pedo_area_mu_3303302.shp").to_crs(4326)

gdf_relevo_ped = geopandas.tools.sjoin(gdf_relevo, gdf_pedologia[['leg_ordem','legenda_2','geometry']], predicate="within", how='left')

_dummies = pd.get_dummies(gdf_relevo_ped, columns = None, drop_first = False)

_dummies = _dummies.rename(columns={"leg_ordem_ARGISSOLO": "Argilossolo"
                            , "leg_ordem_GLEISSOLO": "Gleissolo"
                            , "legenda_2_ARGISSOLO AMARELO": "Argilossolo_Amarelo"
                            , "legenda_2_ARGISSOLO VERMELHO-AMARELO": "Argilossolo_Vermelho_Amarelo"
                            , "legenda_2_GLEISSOLO MELÂNICO": "Gleissolo_Melanico"
                            , "legenda_2_ÁREA URBANA": "Area_Urbana"}).drop(["index_right","leg_ordem_OUTROS"], axis=1)

gdf_relevo = copy.deepcopy(_dummies)

del(gdf_relevo_ped); del(gdf_pedologia); del(_dummies)

"""# Unidade de Conservação"""

gdf_u_conservacao = geopandas.read_file('Unidades_de_Conservacao_Integral.geojson')

DR = gdf_u_conservacao.iloc[[3]]
ST = gdf_u_conservacao.iloc[[4]]
res_difference = DR.overlay(ST, how='difference')

gdf_u_conservacao = pd.concat([gdf_u_conservacao, res_difference])
gdf_u_conservacao = gdf_u_conservacao.drop(3, axis=0)

gdf_relevo_conservacao = geopandas.tools.sjoin(gdf_relevo, gdf_u_conservacao[['tx_tipounidade','tx_planmanejo','geometry']], predicate="within", how='left').drop_duplicates()

_dummies = pd.get_dummies(gdf_relevo_conservacao, columns = None, drop_first = False)

_dummies = _dummies.rename(columns={"tx_tipounidade_Proteção Integral": "Unidades_de_Conservacao_Protecao_Integral"
                            , "tx_tipounidade_ ": "Unidades_de_Conservacao_Protecao_N_Integral"
                            , "tx_planmanejo_SIM": "Plano_de_Manejo"
                            , "tx_planmanejo_NÃO": "Sem_Plano_de_Menejo"}).drop(["index_right"], axis=1).drop_duplicates()

gdf_relevo = copy.deepcopy(_dummies)

del(gdf_u_conservacao); del(DR); del(ST); del(res_difference); del(gdf_relevo_conservacao); del(_dummies)

"""# Informação de Comunidades"""

gdf_comunidades = geopandas.read_file('Comunidades.geojson')

gdf_relevo_comunidades = geopandas.tools.sjoin(gdf_relevo, gdf_comunidades, predicate="within", how='left')

gdf_relevo_comunidades['flg_comunidades'] = gdf_relevo_comunidades['OBJECTID'].map(flg_func)

gdf_relevo_comunidades = gdf_relevo_comunidades.drop(columns=['index_right','OBJECTID','Nome','Area_ha'])

del(gdf_comunidades)

"""# Informações de uso de solo"""

gdf = gdf_relevo_comunidades

variaveis_us = ['agricola'
                ,'exploracao_mineral'
                ,'corpo_hidrico'
                ,'rocha'
                ,'cobertura_vegetal'
                ,'afloramento_rochoso'
                ,'favela'
                ,'ocupacao_desordenada']

for variavel in variaveis_us:

  gdf_uso_solo = geopandas.read_file('Uso_do_solo_' + variavel + '.geojson')

  gdf = geopandas.tools.sjoin(gdf, gdf_uso_solo, predicate="within", how='left')

  gdf['flg_'+ variavel] = gdf['OBJECTID_1'].map(flg_func)

  gdf = gdf.drop(columns=['index_right','OBJECTID_1','Nome','Código','Área','comparacao','Uso_do_Sol','Nome_1','OBS_1','OBS_12','Observacao','OBS','Observ']).drop_duplicates()

del(gdf_uso_solo)

"""# Informação de área de risco"""

gdf_risco = geopandas.read_file('areas_de_risco_Defesa_Civil.geojson')

gdf = geopandas.tools.sjoin(gdf, gdf_risco, predicate="within", how='left')

gdf['flg_areas_de_risco'] = gdf['OBJECTID'].map(flg_func)

gdf = gdf.drop(columns=['index_right','OBJECTID','tx_localid'])

gdf['graurisc'] = gdf['graurisc'].transform(lambda x: x.fillna(0))

gdf = pd.get_dummies(gdf,prefix_sep='_', columns=['Acoes_DC'])

"""# Especificar estação para coordenadas"""

df_voronoi = pd.read_csv('voronoi_prefeitura.csv'
                     ,sep = ','
                     ,decimal='.'
                      )

df_voronoi['geometry'] = df_voronoi['geom'].apply(wkt.loads)
gdf_voronoi = geopandas.GeoDataFrame(df_voronoi, crs='epsg:4326').drop_duplicates() #id 521, que é o Piratininga 2

pointInPolys = geopandas.tools.sjoin(gdf, gdf_voronoi, predicate="within", how='left')

pointInPolys['lat_ocr'] = pointInPolys.geometry.y
pointInPolys['lon_ocr'] = pointInPolys.geometry.x

"""# Salvar arquivo 
Coordenadas e variáveis
"""

pointInPolys.to_csv('coordenadas_mapeadas_variaveis.csv',index=False, encoding = 'utf-8-sig') 
files.download('coordenadas_mapeadas_variaveis.csv')

df_pointInPolys = pd.read_csv('coordenadas_mapeadas_variaveis.csv'
                     ,sep = ','
                     ,decimal='.'
                      )

df_pointInPolys['geometry'] = df_pointInPolys['geometry'].apply(wkt.loads)
pointInPolys = geopandas.GeoDataFrame(df_pointInPolys, crs='epsg:4326')

pointInPolys['lat_ocr'] = pointInPolys.geometry.y
pointInPolys['lon_ocr'] = pointInPolys.geometry.x

"""# Espaços no tempo

O menor horário com ocorrência é id_tempo 117049888, analisar chuva diária (lag 24*60)
"""

lag = 24*60
#11615581 - 13758301

lista_tempo = list(range(11615581,  13758301, lag ))

"""# Informações de chuva"""

df_chuva = pd.read_csv('Tempo_estacao_24h.csv'
                     ,sep = ','
                     ,decimal='.'
                     ,encoding = 'utf-8'
                      )

df_ocorr = pd.read_csv('amostra_aleatoria_coord_100m.csv'
                     ,sep = ','
                     ,decimal='.'
                     ,encoding = 'utf-8'
                      )

df_ocorr['id_tempo_atribuido'] = pd.NaT

for i in range(len(df_ocorr['id_tempo'])):
    for item in lista_tempo:
        if int(item) <= int(df_ocorr.loc[i, 'id_tempo']) < (int(item) + (24 * 60)): # Data-hora atribuida é menor ou igual a da ocorrência
            df_ocorr.loc[i, 'id_tempo_atribuido'] = item

df_ocorr = df_ocorr.dropna()

df_ocorr.loc[:, 'ocorrencia'] = 1

df_ocorr = df_ocorr.merge( pointInPolys[['n_coord','id_estacao']],
                                   right_on=['n_coord'],
                                   left_on=['n_coord'],
                                   how='inner')

valores_distintos = df_ocorr['id_tempo_atribuido'].drop_duplicates().tolist()

df_chuva = df_chuva.merge( df_ocorr,
                                   right_on=['id_estacao','id_tempo_atribuido'],
                                   left_on=['id_estacao','id_tempo'],
                                   how='outer')

df_chuva = df_chuva.merge( pointInPolys.drop(columns=['Acoes_DC_0', 'flg_corpo_hidrico',	'Acoes_DC_1',	'Acoes_DC_2',	'Acoes_DC_3','index_right','lat','long','geom','Sem_Plano_de_Menejo']),
                                   right_on=['id_estacao'],
                                   left_on=['id_estacao'],
                                   how='inner')

# Verificar se n_coord_x é nulo e selecionar as linhas correspondentes
null_rows = df_chuva[df_chuva['n_coord_x'].isnull()]

# Verificar se n_coord_x e n_coord_y são iguais e selecionar as linhas correspondentes
equal_rows = df_chuva[(df_chuva['n_coord_x'] == df_chuva['n_coord_y'])]

# Combinar as linhas que atendem a qualquer uma das condições
filtered_df = pd.concat([null_rows, equal_rows])

del pointInPolys
del df_ocorr
del df_chuva

filtered_df['ocorrencia'] = filtered_df['ocorrencia'].fillna(0)

import numpy as np

# Substituir valores nulos em 'id_tempo_x' por zero
filtered_df['id_tempo_x'] = filtered_df['id_tempo_x'].fillna(0)

# Criar a coluna 'tempo' com base em 'id_tempo_x' e 'id_tempo_atribuido'
filtered_df['id_tempo'] = np.where(filtered_df['id_tempo_x'] != 0, filtered_df['id_tempo_x'], filtered_df['id_tempo_atribuido'])

filtered_df = filtered_df.drop(['id_tempo_x','id_tempo_y', 'n_coord_x' , 'id_tempo_atribuido'], axis=1)

filtered_df

filtered_df.rename(columns={'id_tempo': 'id_tempo_x', 'n_coord_y':'n_coord'}, inplace=True)

#Para remover os duplicados de n_coord e time, onde 1 recebe 0 e outro 1
filtered_df = filtered_df.drop_duplicates()

"""# DataFrame final"""

df_final = filtered_df[['n_coord'
,'id_estacao'
,'ocorrencia'
,'lon_ocr'
,'lat_ocr'
,'id_tempo_x' 
,'tempo'                              
 ,'vintequatrohoras'                                                                                                
 ,'Altitude_numerica'        
 ,'Declividade_numerica'     
 ,'Orientacao_numerica'      
 ,'Curv_Vertical_numerica'   
 ,'Curv_Horizontal_numerica' 
 ,'Declividade_classes_A'    
 ,'Declividade_classes_B'    
 ,'Declividade_classes_C'    
 ,'Orientacao_octantes'      
 ,'Curv_Vertical_3classes'   
 ,'Curv_Vertical_5classes'   
 ,'Curv_Horizontal_3classes' 
 ,'Curv_Horizontal_5classes' 
 ,'Forma_de_terreno_classes' 
 ,'Relevo_sombreado_numerico'
 ,'ADD_divisores_talvegues'
 ,'Vegetacao_Natural_Dominante'	
,'Area_Antropica_Dominante'	
,'legenda_2_Pecuária (pastagens)'
,'Floresta_Ombrofila_Densa'	
,'Formacao_Pioneira'	
,'Floresta_Ombrofila_Densa_Submontana'	
,'Influencia_urbana'	
,'Vegetacao_Secundaria'	
,'Argilossolo'
,'Gleissolo'	
,'Argilossolo_Vermelho_Amarelo'	
,'Gleissolo_Melanico'	
,'Area_Urbana'	
,'Unidades_de_Conservacao_Protecao_N_Integral'	
,'Unidades_de_Conservacao_Protecao_Integral'	
,'Plano_de_Manejo'
 ,'flg_comunidades'
 ,'flg_agricola'
 ,'flg_exploracao_mineral'
 ,'flg_rocha'
 ,'flg_cobertura_vegetal'
 ,'flg_afloramento_rochoso'
 ,'flg_favela'
 ,'flg_ocupacao_desordenada'
 ,'flg_areas_de_risco'
 ,'graurisc']]

df_final.to_csv('df_final_4.csv',index=False, encoding = 'utf-8-sig') 
files.download('df_final_4.csv')