# -*- coding: utf-8 -*-
"""Sample_coordenadas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eeVZOcVH-VwdF1FfzY1mz3uNg5DrwVy0

# Configurações

## Pacotes

### Desinstalar
"""

!pip uninstall -y tensorflow

"""### Instalar"""

!pip install tensorflow

!pip install osmnx

!pip install bridson

!pip install rasterstats

! pip install haversine

"""### Chamar"""

from google.colab import drive
from google.colab import files

import osmnx as ox

from bridson import poisson_disc_samples
import geopandas
from shapely.geometry import Point

import pandas as pd
from rasterstats import  point_query
import numpy as np

import haversine as hs
from haversine import  Unit
import copy

from shapely.ops import nearest_points
from geopy.distance import distance

from shapely import wkt

import random
import numpy as np

# Set a random seed
random.seed(42)
np.random.seed(42)

"""## Funções"""

# Sorteio de coordenadas dentro do polígono

def Poisson_Disc_Random_Points_in_Polygon(polygon, radius_value):

    points = []

    minx = polygon.bounds.loc[0][0]
    miny = polygon.bounds.loc[0][1]
    maxx = polygon.bounds.loc[0][2]
    maxy = polygon.bounds.loc[0][3]

    width = maxx - minx
    height = maxy - miny

    pds = poisson_disc_samples(width=width,
                               height=height,
                               r= radius_value #(0.00125) aproximadamente 100 metros
                               )

    for i in range(len(pds)):
      pnt = Point(tuple(map(sum, zip(pds[i], (minx,miny)))))
      if (polygon.contains(pnt)).bool():
          points.append(pnt)

    return geopandas.GeoSeries(points)

# Limpeza para pontos apenas dentro do município de Niterói

def Clear_Outbounds_Points_in_Polygon(polygon, pnts):

    points = []

    l = len(pnts)

    for i in range(l):
      if (polygon.contains(pnts[i])).bool():
            points.append(pnts[i])   
    return geopandas.GeoSeries(points)

# Atribuição do n_coord mais próximo

def atribuir_n_coord_e_dist(df_ocorrencia, df_coord):
    
    coord_dict = dict(zip(df_coord.geometry, df_coord.n_coord))
    
    df_ocorrencia['dist_to_nearest'] = None
    
    for index, row in df_ocorrencia.iterrows():
        
        nearest = nearest_points(row.geometry, df_coord.geometry.unary_union)[1]

        n_coord = coord_dict[nearest]
        
        dist = distance(row.geometry.coords[0], nearest.coords[0]).meters
        
        df_ocorrencia.loc[index, 'n_coord'] = n_coord
        df_ocorrencia.loc[index, 'dist_to_nearest'] = dist
    
    return df_ocorrencia

#Distância mínima das ocorrências
def Suitable_Points_for_not_Occurence(points_disc_samples, points_occurence, radius ):

  aux1=[list((points_disc_samples[row_id].x,points_disc_samples[row_id].y)) for row_id in range(points_disc_samples.shape[0])]

  for i in range(len(points_occurence)):
    #print(f'')
    aux2=[]
    for j in range(len(aux1)):
      print(f'Amostra, {j} de {len(aux1)} - Ocorrência, {i} de {len(points_occurence)}')
      distancia = hs.haversine((points_occurence[i].x,points_occurence[i].y),
             aux1[j],
             unit=Unit.METERS)
      if distancia > radius:
        aux2.append(aux1[j])
    aux1 = copy.deepcopy(aux2)

  aux2=[]

  for i in range(len(aux1)):
    aux2.append(Point(aux1[i]))

  return geopandas.GeoSeries(aux2)

"""## Conexão com a pasta"""

drive.mount('/content/drive')

cd /content/drive/My Drive/PDPA

"""# Seleção do município de Niterói"""

niteroi_q = "Niterói, Rio de Janeiro, Brazil"

niteroi = ox.geocode_to_gdf(niteroi_q)

#niteroi.crs

"""# Criação de amostras de coordenadas

## Seleção das coordenadas

### Amostra de coordenadas dentro de Niterói
"""

pts_s_ocorrencia = Poisson_Disc_Random_Points_in_Polygon(niteroi,(0.00125))  # aproximadamente 100 metros de raio

"""### Retirar área de lagos"""

gdf_pedologia = geopandas.read_file("pedo_area_mu_3303302.shp")

lagos = gdf_pedologia[gdf_pedologia.loc[:,'legenda' ] == 'Corpo d\'água continental'].unary_union

l = len(pts_s_ocorrencia)
polygon = lagos
pnts = pts_s_ocorrencia
points = []

for i in range(l):
  if (polygon.contains(pnts[i])):
    continue
  else:  
    points.append(pnts[i])

pts_s_ocorrencia = geopandas.GeoSeries(points)

"""### Retirar regiões a nível do mar"""

pts_s_ocorrencia_lista=[list((pts_s_ocorrencia[row_id].x,pts_s_ocorrencia[row_id].y)) for row_id in range(pts_s_ocorrencia.shape[0])]

df_s_ocorrencia = pd.DataFrame(pts_s_ocorrencia_lista, columns=['lon_ocr','lat_ocr'])
df_s_ocorrencia['geometry'] = pts_s_ocorrencia

df_s_ocorrencia.loc[:,'Altitude_numerica']= point_query(df_s_ocorrencia.loc[:,'geometry'], '22S435ZN.tif')

print(min(df_s_ocorrencia['Altitude_numerica']))
print(max(df_s_ocorrencia['Altitude_numerica']))
print(np.mean(df_s_ocorrencia['Altitude_numerica']))

#https://pt-br.topographic-map.com/map-p5151/Niter%C3%B3i/?center=-22.90771%2C-43.10877&zoom=14

df_s_ocorrencia_filt = df_s_ocorrencia[df_s_ocorrencia.loc[:,'Altitude_numerica' ] > 25]

pts_s_ocorrencia_filt = geopandas.GeoSeries(list(df_s_ocorrencia_filt['geometry']))

"""### Criar chave para cada coordenada"""

amostra_aleatoria_coord_100m = geopandas.GeoDataFrame(geometry=pts_s_ocorrencia_filt, crs='EPSG:4326')

amostra_aleatoria_coord_100m['n_coord'] = range(0,len(amostra_aleatoria_coord_100m))

amostra_aleatoria_coord_100m

"""### Salvar o arquivo"""

amostra_aleatoria_coord_100m.to_csv('amostra_aleatoria_coord_100m.csv',index=False, encoding = 'utf-8-sig') 
files.download('amostra_aleatoria_coord_100m.csv')

"""### Leitura do arquivo """

amostra_aleatoria_coord_100m = pd.read_csv('amostra_aleatoria_coord_100m.csv'
                                                  ,sep = ','
                                                  ,decimal='.'
                                                   )

amostra_aleatoria_coord_100m['geometry'] = amostra_aleatoria_coord_100m['geometry'].apply(wkt.loads)
gdf_amostra_aleatoria_coord_100m = geopandas.GeoDataFrame(amostra_aleatoria_coord_100m, crs='epsg:4326')

"""# Inserção das ocorrências

Colocar nas coordenadas criadas em 50m com as informações das ocorrências.
"""

ocorrencias = pd.read_csv('ocorrencias.csv'
                     ,sep = ','
                     ,decimal='.'
                      )

gdf_ocorrencias = geopandas.GeoDataFrame(
    ocorrencias, geometry=geopandas.points_from_xy(x = ocorrencias.lon_ocr, y = ocorrencias.lat_ocr))

"""## Limpeza para pontos apenas dentro do município de Niterói"""

pts_c_ocorrencia = Clear_Outbounds_Points_in_Polygon(niteroi,gdf_ocorrencias.geometry)

df_ocorrencia = ocorrencias.loc[ocorrencias['geometry'].isin(pts_c_ocorrencia)]

df_ocorrencia = df_ocorrencia.reset_index(drop=True)

"""## Atribuição de ocorrências a n_coord

Então aqui entrará a N_coord, se não houver n_coord estipulada em menos de 50 metros cria-se uma nova n_coord. 

 Verificar o ponto com ocorrência mais próximo de outra ocorrência, se tiver em menos de um raio, assumem o mesmo ponto

### Verificação de n_coords pré existentes 

Atribui a ocorrência as coordenadas já numeradas caso já exista um ponto em um raio de 50m próximo.
"""

#df_ocorrencia_com_n_coord_e_dist = atribuir_n_coord_e_dist(df_ocorrencia, gdf_amostra_aleatoria_coord_100m)
df_ocorrencia_com_n_coord_e_dist = atribuir_n_coord_e_dist(df_ocorrencia, gdf_union_ncoord) # Aqui ative apenas se estiver tendo que fazer o looping

_ocorrencia_com_n_coord = df_ocorrencia_com_n_coord_e_dist.drop(
    df_ocorrencia_com_n_coord_e_dist[(df_ocorrencia_com_n_coord_e_dist.loc[:,'dist_to_nearest' ] >= 50)].index
    ).reset_index(drop=True)

"""## Verificação de ocorrências, sem n_coord, que sejam próximas"""

_ocorrencia_s_n_coord = df_ocorrencia_com_n_coord_e_dist.drop(
    df_ocorrencia_com_n_coord_e_dist[(df_ocorrencia_com_n_coord_e_dist.loc[:,'dist_to_nearest' ] < 50)].index
    ).reset_index(drop=True)

df_aux = copy.deepcopy(_ocorrencia_s_n_coord[['id_solicitacao',	'id_tempo',	'lat_ocr',	'lon_ocr',	'geometry']])
df_aux['Ponto_mudanca'] = np.nan
df_aux['Distancia_minima'] = np.nan

linhas = df_aux.shape[0] -1

for i in range(linhas):

    coord_i = (df_aux.at[i,'geometry'].x, df_aux.at[i,'geometry'].y)

    for j in list(range(i+1, linhas+1)):

      coord_j = (df_aux.at[j,'geometry'].x, df_aux.at[j,'geometry'].y)

      distancia = hs.haversine(coord_i,
             coord_j,
             unit=Unit.METERS)

      if   (~np.isnan(df_aux.at[j,'Distancia_minima']) and df_aux.at[j,'Distancia_minima']  >  distancia ) or (np.isnan(df_aux.at[j,'Distancia_minima']) and int(distancia) < 50 ):
 
        df_aux.at[j,'Distancia_minima'] = distancia
        df_aux.at[j,'Ponto_mudanca'] = df_aux.at[i, 'geometry']

# Coordenadas únicas ou fonte
coord_ocorr = geopandas.GeoDataFrame( df_aux.drop(
    df_aux[(~np.isnan(df_aux.loc[:,'Distancia_minima']))].index
    ).reset_index(drop=True), geometry='geometry', crs='EPSG:4326')

#N_coord_inf = len(amostra_aleatoria_coord_100m)
N_coord_inf = len(gdf_union_ncoord) # Aqui ative apenas se estiver tendo que fazer o looping
N_coord_sup = N_coord_inf+ len(coord_ocorr)

coord_ocorr['n_coord'] = range(N_coord_inf,N_coord_sup)

"""## Atualização tabela n_coord"""

#gdf_union_ncoord = pd.concat([gdf_amostra_aleatoria_coord_100m, coord_ocorr[['geometry', 'n_coord']]], ignore_index=True)
gdf_union_ncoord = pd.concat([gdf_union_ncoord, coord_ocorr[['geometry', 'n_coord']]], ignore_index=True) # Aqui ative apenas se estiver tendo que fazer o looping

"""### Atribuição de n_coord a ocorrência

Se ainda houverem atribuições com mais de 50m refazer desde 'atribuição de ocorrencias a n_coord'. Pois o que pode ter ocorrido, uma coordenada que foi atribuida, também possui outra coordenada ligada a ela. 
"""

df_ocorrencia_com_n_coord_e_dist_2 = atribuir_n_coord_e_dist(df_ocorrencia, gdf_union_ncoord)

df_ocorrencia_com_n_coord_e_dist_2

"""# Salvar arquivos

- Informação das coordenadas (geometry, n_coord)

- Informação da ocorrência ( id_tempo,id_solicitacao,geometry, n_coord)
"""

gdf_union_ncoord.to_csv('coordenadas_mapeadas.csv',index=False, encoding = 'utf-8-sig') 
files.download('coordenadas_mapeadas.csv')

n_coord_ocorrencias = df_ocorrencia_com_n_coord_e_dist_2[['id_tempo', 'n_coord']].drop_duplicates()

n_coord_ocorrencias.to_csv('amostra_aleatoria_coord_100m.csv',index=False, encoding = 'utf-8-sig') 
files.download('amostra_aleatoria_coord_100m.csv')